[package]
name = "sprinkler"
version = "0.1.0"
authors = ["Alex Yang <aleozlx@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
fern = "0.5"
chrono = "0.4"
clap = "2.32.0"
regex = "1"
sys-info = "0.5"